# THE DOCKERFILE TO BE USED FOR TESTING LOCALLY.
# BASE WORKING DOCKERFILE-LOCAL EXAMPLE:

# Use the official Python image from the Docker Hub
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install dependencies
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

# Copy the FastAPI application code
COPY . /app

# Command to run the FastAPI app with Uvicorn
EXPOSE 8000

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
# CMD ["python3", "main.py"]
