# PLACE ALL YOUR MODEL CONFIGURATION HERE

modelId: "YOUR AWS BEDROCK MODEL ID"
anthropicVersion: "ANTHROPIC VERSION (IF USING ANY ANTHROPIC MODEL LIKE CLAUDE) -- CURRENTLY 'bedrock-2023-05-31'"
inferenceConfig:
  maxTokens: 1500 # MODIFY AS PER YOUR NEEDS
  temperature: 0.5 # MODIFY AS PER YOUR NEEDS
additionalModelRequestFields:
  top_k: 250 # MODIFY AS PER YOUR NEEDS
